In [85]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

1. 데이터 수집

In [86]:
# 2023 개최 예정 축제 중 주요 분석 축제 선정

festival2023 = pd.read_csv('/content/drive/MyDrive/python_project/festival2023.csv', encoding='cp949')
festival2023

,2023년 지역축제 개최 계획,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도(년),예산(백만원),...,방문객수(前년),NaN,전담조직(축제사무국),NaN,NaN,국비지원\n부처명,담당자,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,국비,...,내국인(명),외국인(명),전담조직명,조직형태,설립근거,NaN,성명,연락처,NaN,NaN
4,1,서울,-,서울뮤직페스티벌,문화예술,10.20~10.22,난지한강공원,혼합형,2019,0,...,"10,000","1,000",서울시 문화예술과,지자체,NaN,NaN,유승운,02-2133-2570,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,1125,제주,-,제주 성읍마을 전통민속 재연축제,전통역사,10월 중,제주 성읍마을 일원,대면,1994,NaN,...,"2,000",NaN,(사)성읍민속마을보존회,NaN,NaN,NaN,오상수,064-710-6791,NaN,NaN
1129,1126,제주,-,정의현성 이전 600주년 기념행사,전통역사,10월 중,제주 성읍마을 일원,대면,2023,NaN,...,-,NaN,성읍1리 마을회,NaN,NaN,NaN,오상수,064-710-6791,NaN,NaN
1130,1127,제주,-,혼인지 축제,전통역사,10월 중,혼인지 일원,대면,2009,NaN,...,"1,000",NaN,온평리 마을회,NaN,NaN,NaN,오상수,064-710-6792,NaN,NaN
1131,1128,제주,-,제21회 예래생태체험축제,생태자연,7.29.~7.30.,논짓물 일원,대면,2000,NaN,...,"1,000",-,예래생태체험축제위원회,위원회,NaN,NaN,김명숙,064-760-4845,NaN,NaN
1132,1129,제주,-,2023 용담용연문화제,문화예술,미정,마애명공원,대면,확인불가,NaN,...,"1,000",20,용담용연문화제 추진위원회,NaN,NaN,NaN,양혁준,064-728-4595,NaN,NaN

In [87]:
# 2022 서울교통공사 승하차인원 정보
subway = pd.read_csv('/content/drive/MyDrive/python/2022_subway station.csv', encoding='EUC-KR')
subway

<ipython-input-87-fdaa94efe433>:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  subway = pd.read_csv('/content/drive/MyDrive/python/2022_subway station.csv', encoding='EUC-KR')

,연번,수송일자,호선,고유역번호(외부역코드),역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2022-01-01,1,150,서울역,승차,120,137,211,439,...,1566,1686,1591,1358,1062,899,1327,814,234,NaN
1,2,2022-01-01,1,150,서울역,하차,113,560,617,910,...,1329,1251,1126,884,764,654,728,416,131,NaN
2,3,2022-01-01,1,151,시청,승차,38,66,101,139,...,474,550,672,528,420,434,491,232,38,NaN
3,4,2022-01-01,1,151,시청,하차,31,195,224,380,...,408,377,354,213,131,98,137,61,24,NaN
4,5,2022-01-01,1,152,종각,승차,44,71,86,158,...,889,964,1024,803,855,1099,1209,255,62,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199075,199076,2022-12-31,8,2826,수진,하차,16,81,64,104,...,287,235,250,196,210,162,252,233,114,46.0
199076,199077,2022-12-31,8,2827,모란,승차,66,68,93,121,...,293,263,273,222,144,156,118,117,56,6.0
199077,199078,2022-12-31,8,2827,모란,하차,13,104,62,131,...,250,264,270,213,207,169,220,223,129,106.0
199078,199079,2022-12-31,8,2828,남위례,승차,23,60,86,150,...,262,260,248,220,134,157,167,151,73,14.0
199079,199080,2022-12-31,8,2828,남위례,하차,22,68,77,149,...,297,323,298,265,240,175,196,178,118,41.0

2. 데이터 전처리

In [88]:
festival2023.dtypes

2023년 지역축제 개최 계획    object
Unnamed: 1          object
Unnamed: 2          object
Unnamed: 3          object
Unnamed: 4          object
Unnamed: 5          object
Unnamed: 6          object
Unnamed: 7          object
Unnamed: 8          object
Unnamed: 9          object
Unnamed: 10         object
Unnamed: 11         object
Unnamed: 12         object
Unnamed: 13         object
Unnamed: 14         object
Unnamed: 15         object
Unnamed: 16         object
Unnamed: 17         object
Unnamed: 18         object
Unnamed: 19         object
Unnamed: 20         object
Unnamed: 21         object
Unnamed: 22         object
dtype: object

In [89]:
festival2023.head(10)

,2023년 지역축제 개최 계획,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도(년),예산(백만원),...,방문객수(前년),NaN,전담조직(축제사무국),NaN,NaN,국비지원\n부처명,담당자,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,국비,...,내국인(명),외국인(명),전담조직명,조직형태,설립근거,NaN,성명,연락처,NaN,NaN
4,1,서울,-,서울뮤직페스티벌,문화예술,10.20~10.22,난지한강공원,혼합형,2019,0,...,"10,000","1,000",서울시 문화예술과,지자체,NaN,NaN,유승운,02-2133-2570,NaN,NaN
5,2,서울,-,차 없는 잠수교 뚜벅뚜벅 축제,문화예술,-상반기:4.30.~7.2. \n매주 일요일(10회)\n-하반기:9.3.~11.1...,잠수교\n(반포한강공원),대면,2022,0,...,"520,000",추산불가,서울시 한강사업본부,지자체,NaN,NaN,강우원,02-3780-0760,NaN,NaN
6,3,서울,-,2023 한강페스티벌,문화예술,"봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...",한강 수상 및 11개 한강공원 일대,대면,2013,0,...,"77,000",추산불가,서울시 한강사업본부,지자체,NaN,NaN,이혜수,02-3780-0718,NaN,NaN
7,4,서울,용산구,제25회 서울드럼페스티벌,문화예술,05.26.~05.27.,노들섬,대면,1999,0,...,"13,839",NaN,서울시 문화예술과,지자체,-,-,한정원,02-2133-2573,NaN,NaN
8,5,서울,송파구,"2023 석촌호수의 가을과 겨울, 그리고 루미나리에",문화예술,10.27.~12.31.(예정),석촌호수,대면,2016,0,...,"200,000","1,000",송파구,자치구,NaN,NaN,유현주,02-2147-2111,NaN,NaN
9,6,서울,송파구,2023 커피 페스티벌,문화예술,10.7.~10.8.(예정),잠실 롯데월드타워 잔디광장,대면,2017,0,...,"100,000",800,"송파구, 한국경제신문",공동주최,NaN,NaN,이학림,02-2147-2116,NaN,NaN

In [ ]:
new_columns = festival2023.iloc[2]
festival2023.columns = new_columns
festival2023

2,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도(년),예산(백만원),...,방문객수(前년),NaN,전담조직(축제사무국),NaN,NaN,국비지원\n부처명,담당자,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도(년),예산(백만원),...,방문객수(前년),NaN,전담조직(축제사무국),NaN,NaN,국비지원\n부처명,담당자,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,국비,...,내국인(명),외국인(명),전담조직명,조직형태,설립근거,NaN,성명,연락처,NaN,NaN
4,1,서울,-,서울뮤직페스티벌,문화예술,10.20~10.22,난지한강공원,혼합형,2019,0,...,"10,000","1,000",서울시 문화예술과,지자체,NaN,NaN,유승운,02-2133-2570,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,1125,제주,-,제주 성읍마을 전통민속 재연축제,전통역사,10월 중,제주 성읍마을 일원,대면,1994,NaN,...,"2,000",NaN,(사)성읍민속마을보존회,NaN,NaN,NaN,오상수,064-710-6791,NaN,NaN
1129,1126,제주,-,정의현성 이전 600주년 기념행사,전통역사,10월 중,제주 성읍마을 일원,대면,2023,NaN,...,-,NaN,성읍1리 마을회,NaN,NaN,NaN,오상수,064-710-6791,NaN,NaN
1130,1127,제주,-,혼인지 축제,전통역사,10월 중,혼인지 일원,대면,2009,NaN,...,"1,000",NaN,온평리 마을회,NaN,NaN,NaN,오상수,064-710-6792,NaN,NaN
1131,1128,제주,-,제21회 예래생태체험축제,생태자연,7.29.~7.30.,논짓물 일원,대면,2000,NaN,...,"1,000",-,예래생태체험축제위원회,위원회,NaN,NaN,김명숙,064-760-4845,NaN,NaN
1132,1129,제주,-,2023 용담용연문화제,문화예술,미정,마애명공원,대면,확인불가,NaN,...,"1,000",20,용담용연문화제 추진위원회,NaN,NaN,NaN,양혁준,064-728-4595,NaN,NaN

In [ ]:
new_column_names = {'광역\n단체명': '광역단체명', '기초\n단체명': '기초단체명'}
festival2023.rename(columns=new_column_names, inplace=True)

In [ ]:
#개최지가 서울인 곳만 추출하기

filtered_festival2023 = festival2023[festival2023['광역단체명'] == '서울']
filtered_festival2023

2,연번,광역단체명,기초단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도(년),예산(백만원),...,방문객수(前년),NaN,전담조직(축제사무국),NaN,NaN,국비지원\n부처명,담당자,NaN,NaN,NaN
4,1,서울,-,서울뮤직페스티벌,문화예술,10.20~10.22,난지한강공원,혼합형,2019,0,...,"10,000","1,000",서울시 문화예술과,지자체,NaN,NaN,유승운,02-2133-2570,NaN,NaN
5,2,서울,-,차 없는 잠수교 뚜벅뚜벅 축제,문화예술,-상반기:4.30.~7.2. \n매주 일요일(10회)\n-하반기:9.3.~11.1...,잠수교\n(반포한강공원),대면,2022,0,...,"520,000",추산불가,서울시 한강사업본부,지자체,NaN,NaN,강우원,02-3780-0760,NaN,NaN
6,3,서울,-,2023 한강페스티벌,문화예술,"봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...",한강 수상 및 11개 한강공원 일대,대면,2013,0,...,"77,000",추산불가,서울시 한강사업본부,지자체,NaN,NaN,이혜수,02-3780-0718,NaN,NaN
7,4,서울,용산구,제25회 서울드럼페스티벌,문화예술,05.26.~05.27.,노들섬,대면,1999,0,...,"13,839",NaN,서울시 문화예술과,지자체,-,-,한정원,02-2133-2573,NaN,NaN
8,5,서울,송파구,"2023 석촌호수의 가을과 겨울, 그리고 루미나리에",문화예술,10.27.~12.31.(예정),석촌호수,대면,2016,0,...,"200,000","1,000",송파구,자치구,NaN,NaN,유현주,02-2147-2111,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,78,서울,영등포구,제2회 영등포 지등축제,문화예술,10월 초,안양천 벚꽃길,대면,2022,NaN,...,800,NaN,영등포문화원,민간단체,NaN,NaN,심규홍,02-2670-3519,NaN,NaN
82,79,서울,성동구,응봉산 개나리축제,"문화예술, 생태자연",3월말,응봉산일대,대면,1998,NaN,...,"3,000",NaN,성동문화재단,재단법인,성동문화재단 설립에 관한 조례(2015년),NaN,전지영,02-2286-5203,NaN,NaN
83,80,서울,성동구,두모포 페스티벌,"문화예술, 전통역사",7월초,옥수역 하부 한강공원,대면,2019,NaN,...,"3,000",NaN,성동문화재단,재단법인,성동문화재단 설립에 관한 조례(2015년),NaN,이대현,02-2286-5207,NaN,NaN
84,81,서울,성동구,태조이성계축제,"문화예술,전통역사",9월중,살곶이체육공원,대면,1999,NaN,...,"3,000",NaN,성동문화재단,재단법인,성동문화재단 설립에 관한 조례(2015년),NaN,전지영,02-2286-5203,NaN,NaN
85,82,서울,성동구,세계민속춤 축제,문화예술,10월초,왕십리광장,대면,2015,NaN,...,"2,000",NaN,성동구,NaN,NaN,NaN,이대현,02-2286-5207,NaN,NaN

In [ ]:
#필요한 데이터만 불러오기

festival2023_2 = filtered_festival2023[['광역단체명','기초단체명', '개최기간', '축제명', '개최방식','방문객수(前년)']]
print(festival2023_2)

2  광역단체명 기초단체명                                               개최기간  \
4     서울     -                                        10.20~10.22
5     서울     -  -상반기:4.30.~7.2.  \n매주 일요일(10회)\n-하반기:9.3.~11.1...
6     서울     -  봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...
7     서울   용산구                                      05.26.~05.27.
8     서울   송파구                                  10.27.~12.31.(예정)
..   ...   ...                                                ...
81    서울  영등포구                                              10월 초
82    서울   성동구                                                3월말
83    서울   성동구                                                7월초
84    서울   성동구                                                9월중
85    서울   성동구                                               10월초

2                            축제명 개최방식 방문객수(前년)
4                       서울뮤직페스티벌  혼합형   10,000
5               차 없는 잠수교 뚜벅뚜벅 축제   대면  520,000
6                    2023 한강페스티벌   대면   77,000
7                  제25회 서울드럼페스티벌   대면   13,839
8   2023 석촌호수의 가을과 겨울, 그리고 루미나리에   대면  200,000
..                           ...  ...      ...
81                  제2회 영등포 지등축제   대면      800
82                     응봉산 개나리축제   대면    3,000
83                      두모포 페스티벌   대면    3,000
84                       태조이성계축제   대면    3,000
85                      세계민속춤 축제   대면    2,000

[82 rows x 6 columns]

In [ ]:
festival2023_2

2,광역단체명,기초단체명,개최기간,축제명,개최방식,방문객수(前년)
4,서울,-,10.20~10.22,서울뮤직페스티벌,혼합형,"10,000"
5,서울,-,-상반기:4.30.~7.2. \n매주 일요일(10회)\n-하반기:9.3.~11.1...,차 없는 잠수교 뚜벅뚜벅 축제,대면,"520,000"
6,서울,-,"봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...",2023 한강페스티벌,대면,"77,000"
7,서울,용산구,05.26.~05.27.,제25회 서울드럼페스티벌,대면,"13,839"
8,서울,송파구,10.27.~12.31.(예정),"2023 석촌호수의 가을과 겨울, 그리고 루미나리에",대면,"200,000"
...,...,...,...,...,...,...
81,서울,영등포구,10월 초,제2회 영등포 지등축제,대면,800
82,서울,성동구,3월말,응봉산 개나리축제,대면,"3,000"
83,서울,성동구,7월초,두모포 페스티벌,대면,"3,000"
84,서울,성동구,9월중,태조이성계축제,대면,"3,000"
85,서울,성동구,10월초,세계민속춤 축제,대면,"2,000"

In [ ]:
#NaN값은 0으로 처리한 후에 다시 분석

festival2023_2['방문객수(전년)'] = festival2023_2['방문객수(前년)'].str.replace(',', '').str.extract(r'(\d+)').fillna(0).astype(int)
print(festival2023_2)

2  광역단체명 기초단체명                                               개최기간  \
4     서울     -                                        10.20~10.22
5     서울     -  -상반기:4.30.~7.2.  \n매주 일요일(10회)\n-하반기:9.3.~11.1...
6     서울     -  봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...
7     서울   용산구                                      05.26.~05.27.
8     서울   송파구                                  10.27.~12.31.(예정)
..   ...   ...                                                ...
81    서울  영등포구                                              10월 초
82    서울   성동구                                                3월말
83    서울   성동구                                                7월초
84    서울   성동구                                                9월중
85    서울   성동구                                               10월초

2                            축제명 개최방식 방문객수(前년)  방문객수(전년)
4                       서울뮤직페스티벌  혼합형   10,000     10000
5               차 없는 잠수교 뚜벅뚜벅 축제   대면  520,000    520000
6                    2023 한강페스티벌   대면   77,000     77000
7                  제25회 서울드럼페스티벌   대면   13,839     13839
8   2023 석촌호수의 가을과 겨울, 그리고 루미나리에   대면  200,000    200000
..                           ...  ...      ...       ...
81                  제2회 영등포 지등축제   대면      800       800
82                     응봉산 개나리축제   대면    3,000      3000
83                      두모포 페스티벌   대면    3,000      3000
84                       태조이성계축제   대면    3,000      3000
85                      세계민속춤 축제   대면    2,000      2000

[82 rows x 7 columns]

<ipython-input-14-1ba59083100d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  festival2023_2['방문객수(전년)'] = festival2023_2['방문객수(前년)'].str.replace(',', '').str.extract(r'(\d+)').fillna(0).astype(int)

In [ ]:
festival2023_2

2,광역단체명,기초단체명,개최기간,축제명,개최방식,방문객수(前년),방문객수(전년)
4,서울,-,10.20~10.22,서울뮤직페스티벌,혼합형,"10,000",10000
5,서울,-,-상반기:4.30.~7.2. \n매주 일요일(10회)\n-하반기:9.3.~11.1...,차 없는 잠수교 뚜벅뚜벅 축제,대면,"520,000",520000
6,서울,-,"봄(5.12.~5.14.).\n여름(7.28.~8.13.),\n가을(10.14.~1...",2023 한강페스티벌,대면,"77,000",77000
7,서울,용산구,05.26.~05.27.,제25회 서울드럼페스티벌,대면,"13,839",13839
8,서울,송파구,10.27.~12.31.(예정),"2023 석촌호수의 가을과 겨울, 그리고 루미나리에",대면,"200,000",200000
...,...,...,...,...,...,...,...
81,서울,영등포구,10월 초,제2회 영등포 지등축제,대면,800,800
82,서울,성동구,3월말,응봉산 개나리축제,대면,"3,000",3000
83,서울,성동구,7월초,두모포 페스티벌,대면,"3,000",3000
84,서울,성동구,9월중,태조이성계축제,대면,"3,000",3000
85,서울,성동구,10월초,세계민속춤 축제,대면,"2,000",2000

3. 데이터 분석

In [ ]:
#방문객수가 많은 것부터 내림차순으로 정리

festival2023_2= festival2023_2.sort_values(by='방문객수(전년)', ascending=False)
festival2023_2.head(10)

2,광역단체명,기초단체명,개최기간,축제명,개최방식,방문객수(前년),방문객수(전년)
79,서울,영등포구,4. 4. ~ 4. 9.(예정),제17회 영등포 여의도 봄꽃축제,대면,"5,230,000",5230000
53,서울,중랑구,5월중,2023 서울장미축제,대면,"730,000",730000
69,서울,마포구,10.14.~10.20.,제22회 서울억새축제,대면,"670,000",670000
10,서울,"종로구, 중구",09.01.~10.29.,제4회 2023서울도시건축비엔날레,대면,"650,000",650000
5,서울,-,-상반기:4.30.~7.2. \n매주 일요일(10회)\n-하반기:9.3.~11.1...,차 없는 잠수교 뚜벅뚜벅 축제,대면,"520,000",520000
43,서울,"서초구, 영등포구",4.30.~6.4. / \n9.16~10.22.,2023 한강달빛 야시장,대면,"495,000",495000
70,서울,-,4.8.~4.16.,서울대공원 벚꽃축제,대면,"273,000",273000
37,서울,서초구,9.23.~9.24.,2023 서리풀페스티벌,대면,"270,000",270000
42,서울,송파구,9.22.~9.24.,제23회 한성백제문화제,대면,"249,000",249000
40,서울,광진구,5.5~5.6,서울동화축제,대면,"200,000",200000

In [ ]:
# 2022 축제 파일에서 억새축제 정보 찾기

festival2022 = pd.read_csv('/content/drive/MyDrive/python_project/2022festival.csv')
festival2022

,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도,예산(백만원),...,Unnamed: 11,Unnamed: 12,방문객수(前년),Unnamed: 14,전담조직(축제사무국),Unnamed: 16,Unnamed: 17,국비지원\n부처명,담당자,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,국비,...,기타,합계,내국인,외국인,전담조직명,조직형태,설립근거,NaN,성명,연락처
1,1.0,서울,본청,2022 서울빛초롱축제,문화예술,11.4.~20.(예정),종로구,오프라인,2009,0,...,700(시비),700,"51,433",NaN,서울관광재단,재단법인,NaN,서울특별시,유가은,02-3788-0845
2,2.0,서울,강동구,제27회 강동선사문화축제,문화예술,22. 10. 8.~10.,서울 암사동 유적 일대,혼합형,1996,-,...,-,617,"10,000",-,강동구,지방자치단체,서울특별시 강동구 선사문화축제에 관한 조례,-,이지용,02-3425-8533
3,3.0,서울,강서구,허준축제,문화예술,10.6.~10.9.,"허준근린공원, 허준박물관 일대",대면,1999,0,...,0,395,"50,000명","1,500명",허준축제추진위원회,임의단체\n(축제추진위원회),없음,NaN,신옥현,02-2600-6455
4,4.0,서울,구로구,2022 구로G페스티벌,기타(주민화합),9.30~10.2,안양천일대,혼합형,2003,0,...,480,800,0,0,구로구 문화관광과,구청,NaN,NaN,정인환,02-860-2060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,940.0,제주,서귀포시,2022 중문칠선녀축제,주민화합,10월 중,중문천제연폭포 일원,대면,1995년,0,...,30,100,0,0,-,-,NaN,NaN,김대응,064-760-4824
942,941.0,제주,제주시,2022 봉개 오름축제,생태자연,10월 중,봉개동 제주4.3평화공원 맞은편,대면,2009년,0,...,20,40,"1,000명",0,봉개동축제추진위원회,임의조직,NaN,NaN,이명기,064-728-4741
943,942.0,제주,제주시,제9회 삼도풍류축제,전통역사,10월 중,관덕정 및 목관아지 일대,대면,2012년,0,...,0,20,860명,96명,삼도2동주민센터\n삼도풍류축제추진위원회,위원회,NaN,NaN,이주명,064-728-4562
944,943.0,제주,본청,제21회 최남단 방어축제,특산물,11월 중,모슬포항 일원,대면,2002년,0,...,43,143,"15,000명",100명,최남단방어축제위원회,위원회,NaN,NaN,김지현,064-710-3243
945,944.0,제주,제주시,제12회 백난아가요제,문화예술,미정,미정,대면,NaN,0,...,0,35,49명,0,제주시 한림읍,지방자치단체,NaN,NaN,양승호,064-728-7613

In [ ]:
#개최지가 서울인 곳만 추출하기

filtered_festival2022 = festival2022[festival2022['축제명'] == '2022 서울억새축제']
filtered_festival2022

,연번,광역\n단체명,기초\n단체명,축제명,축제유형,개최기간,개최장소,개최방식,최초\n개최년도,예산(백만원),...,Unnamed: 11,Unnamed: 12,방문객수(前년),Unnamed: 14,전담조직(축제사무국),Unnamed: 16,Unnamed: 17,국비지원\n부처명,담당자,Unnamed: 20
14,NaN,서울,마포구,2022 서울억새축제,생태자연,10.15~10.21,하늘공원,대면,2002,0,...,0,200,미개최,미개최,서부공원여가센터공원여가과,지자체,해당없음,NaN,항의식,02-300-5981

In [103]:
# 하루동안의 승객수 구해서 '하루승객수'열 만들기
cols =['06시이전', '06-07시간대','07-08시간대','08-09시간대','09-10시간대','10-11시간대','11-12시간대',
       '12-13시간대','13-14시간대','14-15시간대','15-16시간대','16-17시간대','17-18시간대','18-19시간대',
       '19-20시간대','20-21시간대','21-22시간대','22-23시간대','23-24시간대','24시이후']
# 2022 서울교통공사 승하차인원 정보
subway["하루승객수"] = subway.loc[:,cols].sum(axis=1)
subway["하루평균승객수"] = subway["하루승객수"]/19

# 'cols에 해당하는 열의 데이터만 추출 후, 열 방향으로 합을 구함
subway.하루승객수

0         18525.0
1         17087.0
2          5660.0
3          5063.0
4         10046.0
           ...
199075     3490.0
199076     3544.0
199077     3402.0
199078     3421.0
199079     3582.0
Name: 하루승객수, Length: 199080, dtype: float64

In [ ]:
qs = (
    "수송일자 == '2022-10-15'"
    "and 역명 == '마포구청'"
)
emp_filtered15 = subway.query(qs)
emp_filtered[]

KeyError: ignored

In [114]:
qs1 = (
    "수송일자 == '2022-10-15'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1015 = subway.query(qs1)

qs2 = (
    "수송일자 == '2022-10-16'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1016 = subway.query(qs2)

qs3 = (
    "수송일자 == '2022-10-17'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1017 = subway.query(qs3)

qs4 = (
    "수송일자 == '2022-10-18'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1018 = subway.query(qs4)

qs5 = (
    "수송일자 == '2022-10-19'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1019 = subway.query(qs5)

qs6 = (
    "수송일자 == '2022-10-20'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1020 = subway.query(qs6)

qs7 = (
    "수송일자 == '2022-10-21'"
    "and 역명 == '마포구청'"
    "and 승하차구분 == '하차'"
)
sub1021 = subway.query(qs7)

sub1015.loc[:,'하루평균승객수']

156895    568.105263
Name: 하루평균승객수, dtype: float64

In [117]:
sub1016.loc[:,'하루평균승객수']

157439    447.263158
Name: 하루평균승객수, dtype: float64

In [118]:
sub1017.loc[:,'하루평균승객수']

157985    736.421053
Name: 하루평균승객수, dtype: float64

In [119]:
sub1018.loc[:,'하루평균승객수']

158531    751.842105
Name: 하루평균승객수, dtype: float64

In [120]:
sub1019.loc[:,'하루평균승객수']

159077    757.684211
Name: 하루평균승객수, dtype: float64

In [121]:
sub1020.loc[:,'하루평균승객수']

159623    769.0
Name: 하루평균승객수, dtype: float64

In [122]:
sub1021.loc[:,'하루평균승객수']

160169    758.263158
Name: 하루평균승객수, dtype: float64

In [124]:
qs15 = (
    "수송일자 == '2022-10-15'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1015_1 = subway.query(qs15)

qs16 = (
    "수송일자 == '2022-10-16'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1016_1 = subway.query(qs16)

qs17 = (
    "수송일자 == '2022-10-17'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1017_1 = subway.query(qs17)
qs18 = (
    "수송일자 == '2022-10-18'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1018_1 = subway.query(qs18)
qs19 = (
    "수송일자 == '2022-10-19'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1019_1 = subway.query(qs19)
qs20 = (
    "수송일자 == '2022-10-20'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1020_1 = subway.query(qs20)

qs21 = (
    "수송일자 == '2022-10-21'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1021_1 = subway.query(qs21)
sub1015_1.loc[:,'하루평균승객수']

156893    1080.157895
Name: 하루평균승객수, dtype: float64

In [126]:
sub1016_1.loc[:,'하루평균승객수']

157437    1040.684211
Name: 하루평균승객수, dtype: float64

In [125]:
sub1017_1.loc[:,'하루평균승객수']

157983    385.842105
Name: 하루평균승객수, dtype: float64

In [127]:
sub1018_1.loc[:,'하루평균승객수']

158529    397.894737
Name: 하루평균승객수, dtype: float64

In [128]:
sub1019_1.loc[:,'하루평균승객수']

159075    419.473684
Name: 하루평균승객수, dtype: float64

In [129]:
sub1020_1.loc[:,'하루평균승객수']

159621    450.473684
Name: 하루평균승객수, dtype: float64

In [131]:
sub1021_1.loc[:,'하루평균승객수']

160167    514.315789
Name: 하루평균승객수, dtype: float64

In [137]:
qs115 = (
    "수송일자 == '2022-10-15'"
    "and 역명 == '디지털미디어시티'"
    "and 승하차구분 == '하차'"
)
sub1015_2 = subway.query(qs115)

qs116 = (
    "수송일자 == '2022-10-16'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1016_2 = subway.query(qs116)

qs117 = (
    "수송일자 == '2022-10-17'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1017_2 = subway.query(qs117)
qs118 = (
    "수송일자 == '2022-10-18'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1018_2 = subway.query(qs118)
qs119 = (
    "수송일자 == '2022-10-19'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1019_2 = subway.query(qs119)
qs120 = (
    "수송일자 == '2022-10-20'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1020_2 = subway.query(qs120)

qs121 = (
    "수송일자 == '2022-10-21'"
    "and 역명 == '월드컵경기장(성산)'"
    "and 승하차구분 == '하차'"
)
sub1021_2 = subway.query(qs121)
sub1015_2.loc[:,'하루평균승객수']

156891    511.421053
Name: 하루평균승객수, dtype: float64

In [134]:

sub1016_2.loc[:,'하루평균승객수']

156891    511.421053
Name: 하루평균승객수, dtype: float64

In [138]:
sub1017_2.loc[:,'하루평균승객수']

157983    385.842105
Name: 하루평균승객수, dtype: float64

In [139]:
sub1018_2.loc[:,'하루평균승객수']

158529    397.894737
Name: 하루평균승객수, dtype: float64

In [140]:
sub1019_2.loc[:,'하루평균승객수']

159075    419.473684
Name: 하루평균승객수, dtype: float64

In [141]:
sub1020_2.loc[:,'하루평균승객수']

159621    450.473684
Name: 하루평균승객수, dtype: float64

In [142]:
sub1021_2.loc[:,'하루평균승객수']

160167    514.315789
Name: 하루평균승객수, dtype: float64

In [ ]:
qs = (
    "수송일자 == '2022-10-18'"
    "and 역명 == '마포구청'"
)
emp_filtered = subway.query(qs)
emp_filtered.sum(axis=0)

연번                            317063
수송일자            2022-10-182022-10-18
호선                                12
고유역번호(외부역코드)                26212621
역명                          마포구청마포구청
승하차구분                           승차하차
06시이전                            351
06-07시간대                         856
07-08시간대                        2556
08-09시간대                        4248
09-10시간대                        2113
10-11시간대                        1241
11-12시간대                        1063
12-13시간대                        1142
13-14시간대                        1222
14-15시간대                        1131
15-16시간대                        1320
16-17시간대                        1538
17-18시간대                        2010
18-19시간대                        3462
19-20시간대                        2044
20-21시간대                        1302
21-22시간대                        1136
22-23시간대                         907
23-24시간대                         524
24시이후                          154.0
하루승객수                        30320.0
하루평균승객수                  1595.789474
dtype: object

In [ ]:
qs = (
    "수송일자 == '2022-10-19'"
    "and 역명 == '마포구청'"
)
emp_filtered = subway.query(qs)
emp_filtered.sum(axis=0)

연번                            318155
수송일자            2022-10-192022-10-19
호선                                12
고유역번호(외부역코드)                26212621
역명                          마포구청마포구청
승하차구분                           승차하차
06시이전                            369
06-07시간대                         825
07-08시간대                        2527
08-09시간대                        4155
09-10시간대                        2192
10-11시간대                        1217
11-12시간대                        1065
12-13시간대                        1226
13-14시간대                        1252
14-15시간대                        1117
15-16시간대                        1426
16-17시간대                        1486
17-18시간대                        2153
18-19시간대                        3258
19-20시간대                        2111
20-21시간대                        1281
21-22시간대                        1113
22-23시간대                         997
23-24시간대                         597
24시이후                          172.0
하루승객수                        30539.0
하루평균승객수                  1607.315789
dtype: object

In [ ]:
qs = (
    "수송일자 == '2022-10-20'"
    "and 역명 == '마포구청'"
)
emp_filtered = subway.query(qs)
emp_filtered.sum(axis=0)

연번                            319247
수송일자            2022-10-202022-10-20
호선                                12
고유역번호(외부역코드)                26212621
역명                          마포구청마포구청
승하차구분                           승차하차
06시이전                            349
06-07시간대                         872
07-08시간대                        2479
08-09시간대                        4267
09-10시간대                        2322
10-11시간대                        1302
11-12시간대                        1078
12-13시간대                        1337
13-14시간대                        1238
14-15시간대                        1168
15-16시간대                        1365
16-17시간대                        1567
17-18시간대                        2207
18-19시간대                        3299
19-20시간대                        1997
20-21시간대                        1235
21-22시간대                        1226
22-23시간대                        1053
23-24시간대                         545
24시이후                          210.0
하루승객수                        31116.0
하루평균승객수                  1637.684211
dtype: object

In [ ]:
qs = (
    "수송일자 == '2022-10-21'"
    "and 역명 == '마포구청'"
)
emp_filtered = subway.query(qs)
emp_filtered.sum(axis=0)

연번                            320339
수송일자            2022-10-212022-10-21
호선                                12
고유역번호(외부역코드)                26212621
역명                          마포구청마포구청
승하차구분                           승차하차
06시이전                            368
06-07시간대                         822
07-08시간대                        2357
08-09시간대                        4072
09-10시간대                        2009
10-11시간대                        1214
11-12시간대                        1048
12-13시간대                        1311
13-14시간대                        1232
14-15시간대                        1240
15-16시간대                        1490
16-17시간대                        1639
17-18시간대                        2275
18-19시간대                        3458
19-20시간대                        1937
20-21시간대                        1219
21-22시간대                        1032
22-23시간대                        1036
23-24시간대                         709
24시이후                          242.0
하루승객수                        30710.0
하루평균승객수                  1616.315789
dtype: object

In [154]:
subway_time = subway.set_index('수송일자')
s = subway_time.loc['2022-10-08':'2022-10-14']
subw = s[s['역명'] == '월드컵경기장(성산)']

subwa = subw[subw['승하차구분'] == '하차']
subwa.loc[:,'하루평균승객수']

수송일자
2022-10-08    639.684211
2022-10-09    196.105263
2022-10-10    307.263158
2022-10-11    328.894737
2022-10-12    448.105263
2022-10-13    379.631579
2022-10-14    566.526316
Name: 하루평균승객수, dtype: float64